-- 개설과목 수정
-- (개설과목코드, 과목시작일, 과목종료일, 개설과정코드, 교재코드, 과목코드, 출결배점, 필기배점, 실기배점)
CREATE OR REPLACE PROCEDURE PRC_OPENSUB_UPDATE
( V_OPENSUB_CODE        IN TBL_OPENSUB.OPENSUB_CODE%TYPE
, V_OPENSUB_START       IN TBL_OPENSUB.OPENSUB_START%TYPE
, V_OPENSUB_END         IN TBL_OPENSUB.OPENSUB_END%TYPE
, V_OPENCOU_CODE       IN TBL_OPENCOU.OPENCOU_CODE%TYPE
, V_BOOK_CODE           IN TBL_BOOK.BOOK_CODE%TYPE
, V_SUB_CODE            IN TBL_SUB.SUB_CODE%TYPE
, V_OPENSUB_ATTEND      IN TBL_OPENSUB.OPENSUB_ATTEND%TYPE
, V_OPENSUB_WRITE       IN TBL_OPENSUB.OPENSUB_WRITE%TYPE
, V_OPENSUB_PRAC        IN TBL_OPENSUB.OPENSUB_PRAC%TYPE
)
IS
    CHECK_OPENCOU_CODE TBL_OPENCOU.OPENCOU_CODE%TYPE;
    CHECK_OPENSUB_CODE TBL_OPENSUB.OPENSUB_CODE%TYPE;
    OPENSUB_CODE_CHECK TBL_OPENSUB.OPENSUB_CODE%TYPE;
    
    USER_DEFINE_ERROR0 EXCEPTION;
    
    USER_DEFINE_ERROR1 EXCEPTION; -- 과정에 없는 것 에러 발생
    USER_DEFINE_ERROR2 EXCEPTION; -- 과목이 없는 것 에러 발생
    USER_DEFINE_ERROR3 EXCEPTION; -- 기존 과목과 기간 겹칠때 에러
    USER_DEFINE_ERROR4 EXCEPTION; -- 배점 비율 에러 발생
    USER_DEFINE_ERROR5 EXCEPTION; -- 과목 시작일, 종료일 이전 이후일때 에러 발생
    
    V_OPENCOU_START TBL_OPENCOU.OPENCOU_START%TYPE;
    V_OPENCOU_END TBL_OPENCOU.OPENCOU_END%TYPE;
    
    OPENSUB_OLD_START DATE;
    OPENSUB_OLD_END DATE;
    
    CURSOR CUR_CHECK_DATE
    IS
    SELECT OPENSUB_START, OPENSUB_END
    FROM TBL_OPENSUB
    WHERE OPENCOU_CODE = V_OPENCOU_CODE
      AND SUB_CODE != V_SUB_CODE;
BEGIN

    -- 개설과목코드 체크
    SELECT NVL(MAX(OPENSUB_CODE), '0') INTO OPENSUB_CODE_CHECK
    FROM TBL_OPENSUB
    WHERE OPENSUB_CODE = V_OPENSUB_CODE;

    IF (OPENSUB_CODE_CHECK = '0')
        THEN RAISE USER_DEFINE_ERROR0;
    END IF;

    -- 개설 과정 체크
    SELECT NVL(MAX(OPENCOU_CODE), '0') INTO CHECK_OPENCOU_CODE
    FROM TBL_OPENSUB
    WHERE OPENCOU_CODE = V_OPENCOU_CODE;

    IF (CHECK_OPENCOU_CODE = '0')
        THEN RAISE USER_DEFINE_ERROR1;
    END IF;

    -- 개설 과목 체크
    SELECT NVL(MAX(SUB_CODE), '0') INTO CHECK_OPENSUB_CODE
    FROM TBL_OPENSUB
    WHERE SUB_CODE = V_SUB_CODE
    AND OPENCOU_CODE = V_OPENCOU_CODE;

    IF (CHECK_OPENSUB_CODE = '0')
        THEN RAISE USER_DEFINE_ERROR2;
    END IF;


    -- 과목 시작일, 과목 종료일 이전 이후 체크
    SELECT OPENCOU_START, OPENCOU_END INTO V_OPENCOU_START, V_OPENCOU_END
    FROM TBL_OPENCOU
    WHERE OPENCOU_CODE = V_OPENCOU_CODE;
    
    -- 새로 입력한 과목 시작일이 가져온 과정 시작일보다 이전이거나
    -- 새로 입력한 과목 종료일이 가져온 과정 종료일보다 이후이거나
    IF (V_OPENSUB_START < V_OPENCOU_START OR V_OPENSUB_END > V_OPENCOU_END)
        THEN RAISE USER_DEFINE_ERROR3;
    END IF;
    
    -- 총점 100점 초과시 에러발생
    IF (V_OPENSUB_ATTEND + V_OPENSUB_WRITE + V_OPENSUB_PRAC != 100)
        THEN RAISE USER_DEFINE_ERROR4;
    END IF;
    
    
    -- 기존에 있던 과목들과 기간이 겹칠 경우 에러 발생
    OPEN CUR_CHECK_DATE;
    
    LOOP
        FETCH CUR_CHECK_DATE INTO OPENSUB_OLD_START, OPENSUB_OLD_END;
        EXIT WHEN CUR_CHECK_DATE%NOTFOUND;
        
        -- 입력한 과목시작일이 당일, 이전이고 입력한 과목종료일이 당일, 이후이면 에러발생
        IF (V_OPENSUB_START <= OPENSUB_OLD_START AND V_OPENSUB_END >= OPENSUB_OLD_END)
            THEN RAISE USER_DEFINE_ERROR5;
        ELSIF (V_OPENSUB_START <= OPENSUB_OLD_END AND V_OPENSUB_END >= OPENSUB_OLD_END)
            THEN RAISE USER_DEFINE_ERROR5;    
        ELSIF (V_OPENSUB_START >= OPENSUB_OLD_START AND V_OPENSUB_END <= OPENSUB_OLD_END)
            THEN RAISE USER_DEFINE_ERROR5;  
        END IF;
    END LOOP;
    
    CLOSE CUR_CHECK_DATE;
    
    
    UPDATE TBL_OPENSUB
    SET OPENSUB_START = V_OPENSUB_START
    , OPENSUB_END = V_OPENSUB_END
    , OPENSUB_ATTEND = V_OPENSUB_ATTEND
    , OPENSUB_WRITE = V_OPENSUB_WRITE
    , OPENSUB_PRAC = V_OPENSUB_PRAC
    , BOOK_CODE = V_BOOK_CODE
    , OPENCOU_CODE = V_OPENCOU_CODE
    , SUB_CODE = V_SUB_CODE
    WHERE OPENSUB_CODE = V_OPENSUB_CODE;
    
    
    
    EXCEPTION
        WHEN USER_DEFINE_ERROR0
            THEN RAISE_APPLICATION_ERROR(-20961, '개설 과목 코드가 없습니다.');
                ROLLBACK;
                
        WHEN USER_DEFINE_ERROR1
            THEN RAISE_APPLICATION_ERROR(-20961, '개설 과정이 없습니다.');
                ROLLBACK;
            
        WHEN USER_DEFINE_ERROR2
            THEN RAISE_APPLICATION_ERROR(-20962, '해당과정에는 해당 과목이 없습니다.');
                ROLLBACK;
                
        WHEN USER_DEFINE_ERROR3
            THEN RAISE_APPLICATION_ERROR(-20963, '개설 과목은 개설 과정 기간보다 이전/이후일 수 없습니다.');
                ROLLBACK;
                                
        WHEN USER_DEFINE_ERROR4
            THEN RAISE_APPLICATION_ERROR(-20964, '배점의 총합은 100점 이어야 합니다.');
                ROLLBACK;
                
        WHEN USER_DEFINE_ERROR5
            THEN RAISE_APPLICATION_ERROR(-20965, '해당 기간은 진행 중인 과목이 있습니다.');
                ROLLBACK;
                
    --커밋
    COMMIT;
    
END;
---==>> Procedure PRC_OPENSUB_UPDATE이(가) 컴파일되었습니다.








