CREATE OR REPLACE PROCEDURE PRC_OPENSUB_DELETE
( V_OPENSUB_CODE IN TBL_OPENSUB.OPENSUB_CODE%TYPE
)
IS
    CHECK_OPENSUB_CODE NUMBER;
    USER_DEFINE_ERROR1 EXCEPTION;
BEGIN   

    SELECT COUNT(*) INTO CHECK_OPENSUB_CODE
    FROM TBL_OPENSUB
    WHERE OPENSUB_CODE = V_OPENSUB_CODE;
    
    IF (CHECK_OPENSUB_CODE = 0)
        THEN RAISE USER_DEFINE_ERROR1;
    END IF;
    
    -- 삭제
    DELETE
    FROM TBL_OPENSUB
    WHERE OPENSUB_CODE = V_OPENSUB_CODE;
    
    EXCEPTION
        WHEN USER_DEFINE_ERROR1
            THEN RAISE_APPLICATION_ERROR(-20971, '개설과목코드가 없습니다.');
                ROLLBACK;
    
    COMMIT;
END;


