CREATE OR REPLACE PROCEDURE PRC_OPENSUB_DELETE
( V_OPENSUB_CODE IN TBL_OPENSUB.OPENSUB_CODE%TYPE
)
IS
    CHECK_OPENSUB_CODE NUMBER;
    
    V_SCO_ATTEND NUMBER;
    V_SCO_WRITE NUMBER;
    V_SCO_PRAC NUMBER;
    
    USER_DEFINE_ERROR1 EXCEPTION;
    USER_DEFINE_ERROR2 EXCEPTION;
BEGIN   

    SELECT COUNT(*) INTO CHECK_OPENSUB_CODE
    FROM TBL_OPENSUB
    WHERE OPENSUB_CODE = V_OPENSUB_CODE;
    
    IF (CHECK_OPENSUB_CODE = 0)
        THEN RAISE USER_DEFINE_ERROR1;
    END IF;
    
    -- 성적이 들어가 있다면 삭제가 안되게 한다.
    SELECT  SCO_ATTEND, SCO_WRITE, SCO_PRAC INTO V_SCO_ATTEND, V_SCO_WRITE, V_SCO_PRAC
    FROM TBL_SCO
    WHERE OPENSUB_CODE = V_OPENSUB_CODE;
    
    IF (V_SCO_ATTEND >= 0)
        THEN RAISE USER_DEFINE_ERROR2;
    ELSIF (V_SCO_WRITE >= 0)
        THEN RAISE USER_DEFINE_ERROR2;
    ELSIF (V_SCO_PRAC >= 0)
        THEN RAISE USER_DEFINE_ERROR2;
    END IF;
    
    
    
    -- 삭제
    DELETE
    FROM TBL_OPENSUB
    WHERE OPENSUB_CODE = V_OPENSUB_CODE;
    
    EXCEPTION
        WHEN USER_DEFINE_ERROR1
            THEN RAISE_APPLICATION_ERROR(-20971, '개설과목코드가 없습니다.');
                ROLLBACK;
        WHEN USER_DEFINE_ERROR2
            THEN RAISE_APPLICATION_ERROR(-20972, '성적이 입력되어 있어 삭제불가합니다.');
                ROLLBACK;
    
    COMMIT;
END;


