CREATE OR REPLACE FUNCTION FN_TOTAL_SCORE
( V_SCO_CODE     IN TBL_SCO.SCO_CODE%TYPE       -- 성적코드
, V_OPENSUB_CODE IN TBL_OPENSUB.OPENSUB_CODE%TYPE --개설과목코드
)
    RETURN NUMBER
IS
    RESULT NUMBER;
    
    V_ATTEND_PERC TBL_OPENSUB.OPENSUB_ATTEND%TYPE;
    V_WRITE_PERC TBL_OPENSUB.OPENSUB_WRITE%TYPE;
    V_PRAC_PERC TBL_OPENSUB.OPENSUB_PRAC%TYPE;
    
    V_ATTEND_SCORE TBL_SCO.SCO_ATTEND%TYPE;
    V_WRITE_SCORE TBL_SCO.SCO_WRITE%TYPE;
    V_PRAC_SCORE TBL_SCO.SCO_PRAC%TYPE;
    
BEGIN
    -- 해당 수강과목코드의 배점 가져오기
    SELECT NVL(OPENSUB_ATTEND, 0), NVL(OPENSUB_WRITE, 0), NVL(OPENSUB_PRAC, 0)
    INTO V_ATTEND_PERC, V_WRITE_PERC, V_PRAC_PERC
    FROM TBL_OPENSUB
    WHERE OPENSUB_CODE = V_OPENSUB_CODE;
    
    -- 해당 성적코드로 성적 가져오기
    SELECT NVL(SCO_ATTEND, 0), NVL(SCO_WRITE, 0), NVL(SCO_PRAC, 0)
    INTO V_ATTEND_SCORE, V_WRITE_SCORE, V_PRAC_SCORE
    FROM TBL_SCO
    WHERE SCO_CODE = V_SCO_CODE;
    
    
    RESULT := (V_ATTEND_PERC * V_ATTEND_SCORE + V_WRITE_PERC * V_WRITE_SCORE + V_PRAC_PERC * V_PRAC_SCORE)/100;
    RETURN RESULT;
END;
--==>> Function FN_TOTAL_SCORE이(가) 컴파일되었습니다.


COMMIT;
