
--○ 관리자(TBL_ADMIN) 코멘트
COMMENT ON TABLE TBL_ADMIN IS '관리자정보테이블';
COMMENT ON COLUMN TBL_ADMIN.ADMIN_CODE IS '관리자코드';
COMMENT ON COLUMN TBL_ADMIN.ADMIN_PW IS '관리자비밀번호';


--○ 교재(TBL_BOOK) 코멘트
COMMENT ON TABLE TBL_BOOK IS '교재정보테이블';
COMMENT ON COLUMN TBL_BOOK.BOOK_CODE IS '교재코드';
COMMENT ON COLUMN TBL_BOOK.BOOK_NAME IS '교재명';
COMMENT ON COLUMN TBL_BOOK.BOOK_AUTHOR IS '저자';

--○ 강의실(TBL_CLASS) 코멘트
COMMENT ON TABLE TBL_CLASS IS '강의실테이블';
COMMENT ON COLUMN TBL_CLASS.CLASS_CODE IS '강의실코드';
COMMENT ON COLUMN TBL_CLASS.CLASS_NAME IS '강의실명';


--○ 과정(TBL_COURSE) 코멘트
COMMENT ON TABLE TBL_COURSE IS '과정테이블';
COMMENT ON COLUMN TBL_COURSE.COURSE_CODE IS '과정코드';
COMMENT ON COLUMN TBL_COURSE.COURSE_NAME IS '과정명';

--○ 개설과정(TBL_OPENCOU) 코멘트
COMMENT ON TABLE TBL_OPENCOU IS '개설과정테이블';
COMMENT ON COLUMN TBL_OPENCOU.OPENCOU_CODE IS '개설과정코드';
COMMENT ON COLUMN TBL_OPENCOU.COURSE_CODE IS '과정코드';
COMMENT ON COLUMN TBL_OPENCOU.CLASS_CODE IS '강의실코드';
COMMENT ON COLUMN TBL_OPENCOU.OPENCOU_START IS '과정시작일';
COMMENT ON COLUMN TBL_OPENCOU.OPENCOU_END IS '과정종료일';


--○ 개설과목(TBL_OPENSUB) 코멘트
COMMENT ON TABLE TBL_OPENSUB IS '개설과목테이블';
COMMENT ON COLUMN TBL_OPENSUB.OPENSUB_CODE IS '개설과목코드';
COMMENT ON COLUMN TBL_OPENSUB.OPENCOU_CODE IS '개설과정코드';
COMMENT ON COLUMN TBL_OPENSUB.PROF_CODE IS '교수코드';
COMMENT ON COLUMN TBL_OPENSUB.SUB_CODE IS '과목코드';
COMMENT ON COLUMN TBL_OPENSUB.BOOK_CODE IS '교재코드';
COMMENT ON COLUMN TBL_OPENSUB.OPENSUB_DATE IS '과목시작일';
COMMENT ON COLUMN TBL_OPENSUB.OPENSUB_END IS '과목종료일';
COMMENT ON COLUMN TBL_OPENSUB.OPENSUB_ATTEND IS '출결배점';
COMMENT ON COLUMN TBL_OPENSUB.OPENSUB_WRITE IS '출결필기';
COMMENT ON COLUMN TBL_OPENSUB.OPENSUB_PRAC IS '출결실기';


--○ 중도탈락(TBL_OUT) 코멘트
COMMENT ON TABLE TBL_OUT IS '중도탈락테이블';
COMMENT ON COLUMN TBL_OUT.OUT_CODE IS '중도탈락코드';
COMMENT ON COLUMN TBL_OUT.SUGANG_CODE IS '수강신청코드';
COMMENT ON COLUMN TBL_OUT.OUT_REASON_CODE IS '중도탈락사유코드';
COMMENT ON COLUMN TBL_OUT.OUT_DATE IS '중도탈락날짜';


--○ 중도탈락(TBL_OUT_REASON) 코멘트
COMMENT ON TABLE TBL_OUT_REASON IS '중도탈락사유테이블';
COMMENT ON COLUMN TBL_OUT_REASON.OUT_REASON_CODE IS '중도탈락사유코드';
COMMENT ON COLUMN TBL_OUT_REASON.OUT_REASON IS '중도탈락사유';



--○ 교수(TBL_PROF) 코멘트
COMMENT ON TABLE TBL_PROF IS '교수테이블';
COMMENT ON COLUMN TBL_PROF.PROF_CODE IS '교수코드';
COMMENT ON COLUMN TBL_PROF.PROF_PW IS '교수비밀번호';
COMMENT ON COLUMN TBL_PROF.PROF_NAME IS '교수명';
COMMENT ON COLUMN TBL_PROF.PROF_RRN IS '주민번호';
COMMENT ON COLUMN TBL_PROF.PROF_TEL IS '전화번호';




--○ 성적(TBL_SCO) 코멘트
COMMENT ON TABLE TBL_SCO IS '성적테이블';
COMMENT ON COLUMN TBL_SCO.SCO_CODE IS '성적코드';
COMMENT ON COLUMN TBL_SCO.OPENSUB_CODE IS '개설과목코드';
COMMENT ON COLUMN TBL_SCO.SUGANG_CODE IS '수강코드';
COMMENT ON COLUMN TBL_SCO.SCO_ATTEND IS '출결';
COMMENT ON COLUMN TBL_SCO.SCO_WRITE IS '필기';
COMMENT ON COLUMN TBL_SCO.SCO_PRAC IS '실기';



STD_NUMBER
STD_NAME
STD_PW
STD_RRN


--○ 학생(TBL_STD) 코멘트
COMMENT ON TABLE TBL_STD IS '학생테이블';
COMMENT ON COLUMN TBL_STD.STD_NUMBER IS '학번';
COMMENT ON COLUMN TBL_STD.STD_NAME IS '학생명';
COMMENT ON COLUMN TBL_STD.STD_PW IS '비밀번호';
COMMENT ON COLUMN TBL_STD.STD_RRN IS '주민번호';

--○ 과목(TBL_SUB) 코멘트
COMMENT ON TABLE TBL_SUB IS '과목테이블';
COMMENT ON COLUMN TBL_SUB.SUB_CODE IS '과목코드';
COMMENT ON COLUMN TBL_SUB.SUB_CODE IS '과목명';


--○ 수강(TBL_SUGANG) 코멘트
COMMENT ON TABLE TBL_SUGANG IS '수강테이블';
COMMENT ON COLUMN TBL_SUGANG.SUGANG_CODE IS '수강코드';
COMMENT ON COLUMN TBL_SUGANG.OPENCOU_CODE IS '개설과정코드';
COMMENT ON COLUMN TBL_SUGANG.STD_NUMBER IS '학번';
COMMENT ON COLUMN TBL_SUGANG.SUGANG_DATE IS '수강신청일';




























