
CREATE OR REPLACE TRIGGER PRC_SUB_DELETE1
    BEFORE
    DELETE ON TBL_SUB
    FOR EACH ROW
BEGIN
    DELETE 
    FROM TBL_OPENSUB
    WHERE SUB_CODE = :OLD.SUB_CODE;
END;
--==>> Trigger PRC_SUB_DELETE1이(가) 컴파일되었습니다.

COMMIT;